### ISSUE TITLE
[Niconico] I want to add a feature which allows users to specify the fontsize coefficient

### ISSUE THREAD

**Issue by alexvong1995** [m13253/danmaku2ass#14]
I find the moving comment is too small, but when I increase the fontsize, the subtitle get out of screen.
Therefore, I want to add a feature which allows users to specify the fontsize coefficient since everyone have different taste.

I have implenmented it in my fork and I want to know how you guys think about it.
I will create a pull request after the NicoFox pull request is done.
Thanks!

**Comment by m13253** [comment]
> I find the moving comment is too small, but when I increase the fontsize, the subtitle get out of screen.

Isn't it the `-fs` option?

I can not figure out the problem you are experiencing. Would you please attach your command line and a screenshot?

**Comment by alexvong1995** [comment]
Yes I know about the -fs --fontsize flag. Sory maybe I express it wrongly. I don't mean there is bug about the fontsize. What I mean is there could be an enhancement made to let the user define different fontsize with different comment type by giving the coefficient ( moving, big, small, reverse-moving... ). Currently, the coefficient is hard-code as 1.44 and 0.64 for big and small comment.

For example, 
There are 3 fontsize coefficients:
coef_moving, coef_big, coef_small

The usage is:
-coef MOVING+BIG+SMALL or --fontsize-coef MOVING+BIG+SMALL

The default fontsize coefficients are:
2+1.44+0.64 which I prefer
or maybe 1+1.44+0.64
to keep consistency with current version

I come up with this because I personally prefer having moving comment big, while keeping the others small. I have tried this with niconico and it seems to be working. How do you think about this feature?

**Comment by m13253** [comment]
Got your idea.

First, there is a history problem ― I firstly write Danmaku2ASS for Bilibili, a Chinese danmaku site, where font sizes are hard-coded in XML files. The default size for Bilibili is 25px, so I made a --fontsize option to multiply the font size by (n/25) times.

But things in Niconico are differ, it writes "big" and "small" instead of size in pixels. So I measured the actual size of Niconico official player (Ginza version at that time), and calculated the coefficient to match the size.

I don't think there is such an option to specify sizes differently with moving comments or still comments in the Niconico official player. (Maybe I was wrong?) I try to achieve the behavior of the official player.

Moreover, it may break the playback of Toukome with advanced effects.

Anyway, you can keep your fork for your personal use. If anyone else has the same request as you, or if you have a better reason, I will consider this issue again.

BTW, are you good at Japanese? Would you please help me review the Japanese translation? I am not good at Japanese and I only passed Japanese level N5 test.

**Comment by m13253** [comment]
Got your idea.

First, there is a history problem ― I firstly write Danmaku2ASS for Bilibili, a Chinese danmaku site, where font sizes are hard-coded in XML files. The default size for Bilibili is 25px, so I made a --fontsize option to multiply the font size by (n/25) times.

But things in Niconico are differ, it writes "big" and "small" instead of size in pixels. So I measured the actual size of Niconico official player (Ginza version at that time), and calculated the coefficient to match the size.

I don't think there is such an option to specify sizes differently with moving comments or still comments in the Niconico official player. (Maybe I was wrong?) I try to achieve the behavior of the official player.

Moreover, it may break the playback of Toukome with advanced effects.

Anyway, you can keep your fork for your personal use. If anyone else has the same request as you, or if you have a better reason, I will consider this issue again.

BTW, are you good at Japanese? Would you please help me review the Japanese translation? I am not good at Japanese and I only passed Japanese level N5.

**Comment by alexvong1995** [comment]
I see your point. It is good to keep it as close as orginal .  Breaking old stuff is not good indeed.
I am not good at Japanese either but I think I can ask my friends to see if they are interested in it. :smile:

**Comment by m13253** [comment]
So, please keep your personal fork and use it yourself. :sweat_smile:

And, if you are satisfied with my answer, please close this issue.

> I am not good at Japanese

Then why you watch Niconico? :laughing:

**Comment by alexvong1995** [comment]
ok
I don't know. Someone introduces it to me and I start watching it. :P
Yes you are right. I need to learn it when I have time. Probably summer...
