### ISSUE TITLE
 Add auto dectection of resolution using mplayer2 

### ISSUE THREAD

**Issue by alexvong1995** [m13253/danmaku2ass#17]
What do you think about adding auto detection of resolution?

Do you think using mplayer2 for this purpose is suitable?
I choose mplayer2 because I presume that many GNU/Linux distros will have it installed
but I haven't think about Windows/Mac users yet. Is this script supposed to be cross-platform?

I will dealt with it later if you think this addition is ok.

https://github.com/alexvong1995/danmaku2ass/commit/26fa47778a80bd9c0cb97562c93283d0586e4465

Btw, have you watched the latest anime by SHAFT? I love the op :P

**Comment by m13253** [comment]
Danmaku2ASS only deals with comments. Other things need to be done by frontends.

If you want to play movies on Bilibili, use the frontend [BiliDan](https://github.com/m13253/BiliDan).

BiliDan is based on MPV (instead of MPlayer2). Though MPV has everything from MPlayer2.

BiliDan deals everything, ranging from resolution detection, comment conversion with Danmaku2ASS, to buffering and steaming, for you.

**Comment by alexvong1995** [comment]
I see. So Danmaku2ASS is invoked by frontends, instead of being a standalone script. It is indeed better to seperate parts that does different things, making things simpler and clearer. Maybe I should try the same. Thanks!

**Comment by m13253** [comment]
> Have fun during your holiday. They are precious!

Happy New Year!
新年快乐！
